### ISSUE TITLE
Crash (while running in demo mode)

### ISSUE THREAD

**Issue by d4f5409d** [Quicksticks-oss/Rust-TradeOgre-Bot#5]
OS: Zorin OS
Logs:

``` bash
 * 2024-03-03 13:14:59 [INFO] : Price: 61699.09, Similarities: 0.5774, Slope: 0, Action: hold
 * 2024-03-03 13:15:36 [INFO] : Price: 62000.00, Similarities: 0.7071, Slope: 0, Action: sell
 * 2024-03-03 13:16:37 [INFO] : Price: 62000.00, Similarities: 0.7746, Slope: 301, Action: sell
 * 2024-03-03 13:21:42 [INFO] : Price: 62000.00, Similarities: 0.7746, Slope: 150, Action: buy
 * 2024-03-03 13:28:48 [INFO] : Price: 61900.00, Similarities: 0.7746, Slope: 90, Action: buy
 * 2024-03-03 13:30:51 [INFO] : Price: 61900.00, Similarities: 0.8944, Slope: 40, Action: buy
 * 2024-03-03 13:32:52 [INFO] : Price: 61900.00, Similarities: 1.0000, Slope: -30, Action: sell
 * 2024-03-03 13:32:53 [POSI] : Trades: 0, Balance: 60.00, Ride: 60.20
 * 2024-03-03 13:32:53 [NEGA] : Selling USDT-BTC at price 61900.00!
thread 'main' panicked at src/net/trading_api.rs:76:78:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by d4f5409d** [comment]
Another one:

```bash
 * 2024-03-03 15:16:05 [POSI] : Starting TradeOgre Bot...
 * 2024-03-03 15:16:05 [INFO] : Market: ETH-USDT
 * 2024-03-03 15:16:05 [INFO] : API Sleep: 512
 * 2024-03-03 15:16:05 [INFO] : Max Sticks: 16
 * 2024-03-03 15:16:05 [INFO] : Max Slope Sticks: 5
 * 2024-03-03 15:16:05 [INFO] : Slope Threshold: -10
 * 2024-03-03 15:16:05 [INFO] : Threshold: 0.95
 * 2024-03-03 15:16:05 [POSI] : Cache downloaded or found!
 * 2024-03-03 15:16:05 [MEDI] : Loading vecdb csv data...
 * 2024-03-03 15:16:05 [MEDI] : Initializing Vector DB...
 * 2024-03-03 15:16:22 [POSI] : Vector DB loaded.
 * 2024-03-03 15:16:22 [POSI] : Time taken to query vec db: 9.727443ms
 * 2024-03-03 15:16:22 [MEDI] : Initializing trading API...
 * 2024-03-03 15:16:22 [POSI] : Trading will now begin!
 * 2024-03-03 15:16:22 [POSI] : =========================
 * 2024-03-03 15:16:22 [INFO] : Price: 3446.14, Similarities: 1.0000, Slope: 0, Action: hold
 * 2024-03-03 15:16:22 [INFO] : Trades: 0, Balance: 60.00, Ride: 60.00
 * 2024-03-03 15:16:22 [WARN] : Slope is 0.0, most likely start of program.
 * 2024-03-03 15:16:22 [MEDI] : Holding ETH-USDT at price 3446.14!
 * 2024-03-03 15:22:20 [INFO] : Price: 3397.93, Similarities: 1.0000, Slope: 0, Action: buy
 * 2024-03-03 15:22:20 [POSI] : Trades: 1, Balance: 60.00, Ride: 59.16
 * 2024-03-03 15:22:20 [WARN] : Slope is 0.0, most likely start of program.
 * 2024-03-03 15:22:20 [POSI] : Purchased ETH-USDT at price 3397.93!
thread 'main' panicked at src/net/trading_api.rs:76:78:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by d4f5409d** [comment]
Here it does not recognize I have started the bot just right now:

```bash
* 2024-03-03 15:14:28 [POSI] : Starting TradeOgre Bot...
 * 2024-03-03 15:14:28 [INFO] : Market: USDC-USDT
 * 2024-03-03 15:14:28 [INFO] : API Sleep: 512
 * 2024-03-03 15:14:28 [INFO] : Max Sticks: 16
 * 2024-03-03 15:14:28 [INFO] : Max Slope Sticks: 5
 * 2024-03-03 15:14:28 [INFO] : Slope Threshold: -10
 * 2024-03-03 15:14:28 [INFO] : Threshold: 0.95
 * 2024-03-03 15:14:28 [POSI] : Cache downloaded or found!
 * 2024-03-03 15:14:28 [MEDI] : Loading vecdb csv data...
 * 2024-03-03 15:14:28 [MEDI] : Initializing Vector DB...
 * 2024-03-03 15:14:44 [POSI] : Vector DB loaded.
 * 2024-03-03 15:14:44 [POSI] : Time taken to query vec db: 9.501565ms
 * 2024-03-03 15:14:44 [MEDI] : Initializing trading API...
 * 2024-03-03 15:14:44 [POSI] : Trading will now begin!
 * 2024-03-03 15:14:44 [POSI] : =========================
 * 2024-03-03 15:14:45 [INFO] : Price: 1.00, Similarities: 0.9354, Slope: 0, Action: buy
```

No such thing as
```
 * 2024-03-03 15:22:20 [WARN] : Slope is 0.0, most likely start of program.
```
